* 2016
** Looking back to 2015
2015 was the year I finally gained independence. It was all about
expanding my horizons -- mainly trying out stuff, expanding hobbies, and see
what I like. I tried out rock climbing, music making, serious cycling, hiking,
cooking and more. Some will stick, some won't.

Late 2015 I also had a slight depression around my birthday -- I felt that I had
no friends. After some digging I think I don't have any **close friends**. Most
of my friends here are just peers, who only come for a laugh and then leave.

Prior to the slight depression I also broke my right wrist, and sprained my
left. The subsequent weeks were the most inactive I've been in a while. 
** Goals
*** Greatly expand social circle
To find the people who I can be close with, I need to let myself out there
first. Random socializing has always been a hard thing to do for me. Well, I'm
out of school, work's not getting there. 

There's no way around it -- I'll have to put myself out there and meet new
people proactively.
*** Turn your hobbies into a habit
I've tried a lot of new hobbies, but they rarely stick, and there are times when
I give up on them easily. Really, the only consistent thing was biking. That's
because it was part of my schedule -- I bike at least part way to work.

Now, when I find a hobby that I like I need to figure out a way to integrate it
into my schedule. (Org should be able to help out with that)
*** Stay healthy
Last weeks of 2015 my Mom gave me a scare by checking my blood pressure and
seeing it's slightly above normal. Looks like I'm not the invincible man I think
so anymore. Not to mention my general sluggishness after not exercising due to
the wrist injuries.

And so staying healthy is one of the main reasons I decided to be a pescetarian
(main motivation is ethics after that brazilian steakhouse in san antonio). But
that also means I need to figure exercise as part of my daily routine. Strength,
endurance, and cardio. Everyday.

